" Colorscheme
let g:molokai_original = 1

" Start key for custom key binds.
let mapleader=" "

" BASICS
    set nocompatible
    syntax enable
    filetype indent plugin on
    set number
    set relativenumber
    set showcmd                 " shows the latest command in bottom right corner.
    set cursorline              " highlight current line.
    set lazyredraw              " redraw only when we need to.
    set showmatch               " highlight matching [{()}]
    set nomodeline              " security bug, might be fixed though.

" Tabs
    set tabstop=4
    set softtabstop=4
    set expandtab
    set shiftwidth=4

" Searching
    set incsearch               " search as characters are entered.
    set hlsearch                " highlight mathces.

" Turn off search highlight
    nnoremap <leader>h :nohlsearch<CR>

" Folds
    set foldenable
    set foldlevelstart=10       " open all folds with up to 10 levels initially.
    set foldnestmax=10          " max number of folds.
    set foldmethod=indent       " fold based on indent level.

" Movement
    " treat every line as a real line.
    noremap j gj
    noremap k gk

    " move to beginning/end of line.
    noremap B ^
    noremap E $
    noremap ^ <nop>
    noremap $ <nop>

" Vim recursivley searches.
set path+=**

" Show <TAB> completion options.
set wildmode=longest,list,full
set wildmenu

" Delete trailing whitespace on write.
autocmd BufWritePre * %s/\s\+$//e

augroup configgroup
	autocmd!
	autocmd FileType c setlocal tabstop=8
	autocmd FileType c setlocal noexpandtab
	autocmd FileType c setlocal shiftwidth=8
	autocmd FileType c setlocal softtabstop=8
	autocmd FileType c setlocal cindent
augroup END
" Net Browser
let g:netrw_banner=0
let g:netrw_altv=1
let g:netrw_liststyle=3
