#!/bin/sh

sxhkd &

# Basics
bspc monitor ${MON1} -d 1 2 3 4 5
bspc monitor ${MON0} -d 6 7 8 9 0

bspc config border_width		2
bspc config window_gap			12

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focused_border_color	#FF0000
bspc config active_border_color		#FF0000

# BSPWM rules
bspc rule -a Zathura monitor=${MON0} desktop='^7' \
    follow=on focus=on
bspc rule -a MuPDF monitor=${MON0} desktop='^7' \
    follow=on focus=on
bspc rule -a firefox monitor=${MON0} desktop='^1' \
    follow=on focus=on

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on

# Autostart
xsetroot -cursor_name left_ptr
feh --randomize --bg-fill --no-fehbg ~/utils/wallpapers/Landscapes &
$HOME/.config/polybar/launch.sh &

# Load old session
if [[ -e ${BSPWM_STATE} ]]; then
	sel=$(echo -e "yes\nno" | dmenu -p "Load old session?")
	if [[ $sel = "yes" ]]; then
		bspc wm --load-state ${BSPWM_STATE};
		bspc wm --adopt-orphans;
		rm ${BSPWM_STATE}
	fi
fi
