#!/bin/sh

autostart
. setup_monitors
# Basics
bspc monitor ${MON0} -d 1 2 3 4 5
bspc monitor ${MON1} -d 6 7 8 9 10

bspc config border_width		        2
bspc config window_gap			        10

bspc config split_ratio			        0.52
bspc config borderless_monocle		    true
bspc config gapless_monocle		        true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       true
bspc config pointer_follows_monitor     true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors     true

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on
scratch

# Rules
bspc rule -a Zathura state=tiled monitor=^1 desktop=^2
bspc rule -a Firefox monitor=^2 desktop=^1
