#!/bin/sh

# Handle bspwm gaps.
curr=$(bspc config window_gap)
amount=5

case $1 in
    gapon)
        bspc config window_gap 10
        ;;
    gapoff)
        bspc config window_gap 0
        ;;
    inc)
        bspc config window_gap $(expr $curr + $amount)
        ;;
    dec)
        bspc config window_gap $(expr $curr - $amount)
        ;;
esac
