#!/usr/bin/sh

# Prompt for reboot or shutdown.

prmtrn() {
	sel=$(echo -e "yes\nno" | dmenu -p "Do you want to $1")
	echo $sel
}

opt="cancel\nreboot\nshutdown"

sel=$(echo -e $opt | dmenu -p "What to do?")

if [ $sel = "cancel" ]; then
    exit
fi

chc=$(prmtrn $sel)

if [ $chc = "no" ]; then
	exit
fi

case $sel in
	reboot)
		reboot
		;;
	shutdown)
		poweroff
		;;
esac
